import { Metadata } from "next"

export const metadata:Metadata= {
  title: {
    absolute:"",
    default:"Next.js Tutorial - Parag Jain", // when we want to provide a fallback title for a child route segment they don't explicitly specify a title
    template:"%s | Neha Tobacco", //
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
